[versions]
jda = "5.0.0-beta.18"
logback = "1.4.14"

[libraries]
jda = { group = "net.dv8tion", name = "JDA", version.ref = "jda" }
logback = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback" }
